fix: Update @serialize-javascript to address @json5 vulnerability #26
looker-open-source/viz-aster-marketplace pull request #11
Opened 2024-07-25 16:40 UTC by elivillalejos

- Upgrading serialize-javascript dependency to address Cross-site Scripting (XSS) and Arbitrary Code Injection affecting serialize-javascript.
- Upgrading outdated code from d3 libraries.

2024-07-30 17:55 UTC, yesudeep requested changes

2024-07-30 17:55 UTC, yesudeep commented on src/aster_plot_src.js
> +        // console.log('Radius not set. Defaulting to max score: ' + getMaxOfArray(all_scores))
Why has this been commented? Is this console logging required?

2024-07-31 13:15 UTC, elivillalejos commented on src/aster_plot_src.js
> +        // console.log('Radius not set. Defaulting to max score: ' + getMaxOfArray(all_scores))
Just clearing out the console since it's not required.

2024-08-06 20:06 UTC, yesudeep approved these changes

2024-08-06 20:06 UTC, merged